services:
  auction-server:
    image: ghcr.io/huangnosimp/auction/auction-server:latest
    restart: unless-stopped
    ports:
      - "26676:26676"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DIR=/app/logs
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 400M
