package vn.io.huangnosimp.protocol;

public enum ActionType {
    LOGIN,
    REGISTER,
    LOGOUT,
    DEPOSIT,
    WITHDRAW,

    CREATE_AUCTION,
    PLACE_BID,
    JOIN_ROOM,
    LEAVE_ROOM,
    CANCEL_AUCTION,
    BUY_NOW,

    ADMIN_GET_ALL_MEMBERS,
    ADMIN_LOCK_MEMBER,
    ADMIN_UNLOCK_MEMBER,
    ADMIN_GET_ALL_AUCTIONS,
    ADMIN_FORCE_CANCEL,
    ADMIN_GET_REVENUE,

    REGISTER_AUTO_BID,
    UNREGISTER_AUTO_BID,

    NOTIFICATION,

    GET_DASHBOARD_INFO,
    GET_AUCTION_DETAIL,
}
