package vn.io.huangnosimp.protocol;

public enum ActionType {
    LOGIN,
    REGISTER,
    LOGOUT,
    DEPOSIT,
    WITHDRAW,

    GET_DASHBOARD_INFO,
    GET_ACTIVE_AUCTIONS,
    GET_AUCTION_DETAIL,
    CREATE_AUCTION,
    PLACE_BID,
    JOIN_ROOM,
    LEAVE_ROOM,
    CANCEL_AUCTION,

    ADMIN_GET_ALL_MEMBERS,
    ADMIN_LOCK_MEMBER,
    ADMIN_UNLOCK_MEMBER,
    ADMIN_GET_ALL_AUCTIONS,
    ADMIN_FORCE_CANCEL,
    ADMIN_GET_REVENUE,

    NOTIFICATION
}
