package vn.io.huangnosimp.protocol;

public enum ActionType {
    LOGIN,
    REGISTER,
    LOGOUT,
    DEPOSIT,
    WITHDRAW,

    CREATE_AUCTION,
    PLACE_BID,
    JOIN_ROOM,
    LEAVE_ROOM,
    CANCEL_AUCTION,
    BUY_NOW,
    GET_CLOUDINARY_UPLOAD_SIGNATURE,
    GET_SERVER_TIME,

    ADMIN_GET_ALL_MEMBERS,
    ADMIN_LOCK_MEMBER,
    ADMIN_UNLOCK_MEMBER,
    ADMIN_GET_ALL_AUCTIONS,
    ADMIN_FORCE_CANCEL,
    ADMIN_GET_REVENUE,

    REGISTER_AUTO_BID,
    UNREGISTER_AUTO_BID,
    GET_USER_AUTO_BIDS,

    NOTIFICATION,

    GET_DASHBOARD_INFO,
    GET_AUCTION_DETAIL,
    GET_JOINING_AUCTION_CARD,
    GET_PUBLIC_AUCTION_CARD,
    GET_POSTED_AUCTION_CARD,
    GET_WON_AUCTION,
    GET_ENDED_POSTED_AUCTION,
}
